palavra = input('Digite algo: ')
print(f'A palavra digitada possui números ou letras? {palavra.isalnum()}')
print(f'A palavra possui apenas letras? {palavra.isalpha()}')
print(f'A palavra está toda minúscula? {palavra.islower()}')
print(f'Possui somente espações na palavra? {palavra.isspace()}')
print(f'As palavras que dão inicia as palavras está com a primeira letra maiúscula? {palavra.istitle()}')
print(f'A palavra está maiúscula? {palavra.isupper()}')
print(f'A palavra é um número decimal? {palavra.isdecimal()}')
print(f'São apenas digítos? {palavra.isdigit()}')
print(f'É um número? {palavra.isnumeric()}')
